web:
  build: .
  ports:
    - 8000:8000
  volumes:
    - .:/voltronflamingo/
  entrypoint: /usr/local/bin/python
  command: manage.py runserver 0.0.0.0:8000

tests:
  build: .
  volumes:
    - .:/voltronflamingo/
  entrypoint: /usr/local/bin/python
  command: manage.py test
