# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
    ]
